languageCode = "en-us"
title = "R, Econometrics, High Performance"

baseurl = "https://sebkrantz.github.io/Rblog" # Rblog/
publishDir = "docs"
# relativeURLs = true

theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "r-econometrics-high-performance"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "^README", "\\.R$", "\\.Rproj$", ".git"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/SebKrantz"
[[menu.main]]
    name = "Mastodon"
    url = "https://fosstodon.org/@sebkrantz"

[params]
    description = "An blog dedicated to introducing high-performance statistical software and applications."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "https://sebkrantz.github.io/Rblog/favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

